### ISSUE TITLE
Hello, I am a beginner and I would like to know if line 86 of the tokenization_clip. py file loads "/data/tankaibin/Text2VideoDataset/pos. json". What does this file represent and how could I get it.

### ISSUE THREAD

**Issue by cgying** [adxcreative/EERCF#1]
Hello, I am a beginner and I would like to know if line 86 of the tokenization_clip. py file loads "/data/tankaibin/Text2VideoDataset/pos. json". What does this file represent and how could I get it.

**Comment by TheEighthDay** [comment]
Thank you for your reminder. The missing files are here.
[pos.json](https://github.com/adxcreative/EERCF/files/14979309/pos.json)
